/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication6.view;

import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaapplication6.model.Cadastro;
import javaapplication6.model.CadastroConexao;
import javax.swing.JOptionPane;
import sun.util.logging.PlatformLogger;

/**
 *
 * @author flavio
 */
public class CadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpn_cadastro = new javax.swing.JPanel();
        lbl_cadastro = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        lbl_nome = new javax.swing.JLabel();
        lbl_sobrenome = new javax.swing.JLabel();
        lbl_data = new javax.swing.JLabel();
        lbl_idade = new javax.swing.JLabel();
        lbl_sexo = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_nome = new javax.swing.JTextField();
        txt_sobrenome = new javax.swing.JTextField();
        txt_data = new javax.swing.JFormattedTextField();
        txt_idade = new javax.swing.JTextField();
        btn_limpar = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        cmb_sexo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpn_cadastro.setBackground(new java.awt.Color(102, 102, 102));
        jpn_cadastro.setForeground(new java.awt.Color(255, 255, 255));
        jpn_cadastro.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        lbl_cadastro.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbl_cadastro.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cadastro.setText("CADASTRO CLIENTE");

        lbl_id.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(255, 255, 255));
        lbl_id.setText("ID");

        lbl_nome.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_nome.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nome.setText("NOME");

        lbl_sobrenome.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_sobrenome.setForeground(new java.awt.Color(255, 255, 255));
        lbl_sobrenome.setText("SOBRENOME");

        lbl_data.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_data.setForeground(new java.awt.Color(255, 255, 255));
        lbl_data.setText("DATA NASCIMENTO");

        lbl_idade.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_idade.setForeground(new java.awt.Color(255, 255, 255));
        lbl_idade.setText("IDADE");

        lbl_sexo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_sexo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_sexo.setText("SEXO");

        try {
            txt_data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btn_limpar.setText("LIMPAR");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });

        btn_salvar.setText("SALVAR");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        cmb_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sexo", "M", "F" }));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication6/img/network.png"))); // NOI18N

        javax.swing.GroupLayout jpn_cadastroLayout = new javax.swing.GroupLayout(jpn_cadastro);
        jpn_cadastro.setLayout(jpn_cadastroLayout);
        jpn_cadastroLayout.setHorizontalGroup(
            jpn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_cadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpn_cadastroLayout.createSequentialGroup()
                        .addGroup(jpn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn_cadastroLayout.createSequentialGroup()
                                .addGroup(jpn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_id)
                                    .addComponent(lbl_sobrenome)
                                    .addComponent(lbl_nome))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jpn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_id)
                                    .addComponent(txt_nome)
                                    .addComponent(txt_sobrenome, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)))
                            .addGroup(jpn_cadastroLayout.createSequentialGroup()
                                .addComponent(lbl_data)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_data))
                            .addGroup(jpn_cadastroLayout.createSequentialGroup()
                                .addComponent(lbl_idade)
                                .addGap(74, 74, 74)
                                .addComponent(txt_idade))
                            .addGroup(jpn_cadastroLayout.createSequentialGroup()
                                .addComponent(lbl_sexo)
                                .addGap(83, 83, 83)
                                .addGroup(jpn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpn_cadastroLayout.createSequentialGroup()
                                        .addComponent(btn_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cmb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 45, Short.MAX_VALUE)))
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn_cadastroLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(lbl_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jpn_cadastroLayout.setVerticalGroup(
            jpn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_cadastroLayout.createSequentialGroup()
                .addGroup(jpn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpn_cadastroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(lbl_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_id)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nome)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_sobrenome)
                    .addComponent(txt_sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_data)
                    .addComponent(txt_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_idade, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_sexo)
                    .addComponent(cmb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jpn_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_limpar, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(btn_salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        getContentPane().add(jpn_cadastro, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
       LimparCampos();
    }//GEN-LAST:event_btn_limparActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        Cadastro.nome=txt_nome.getText();
        Cadastro.sobrenome=txt_sobrenome.getText();
        Cadastro.idade=Integer.parseInt(txt_idade.getText());
        Cadastro.sexo=cmb_sexo.getSelectedItem().toString();
        
        SimpleDateFormat sd=new SimpleDateFormat("dd/MM/yyyy");
        
        try
        {
            java.util.Date date=sd.parse(txt_data.getText());
            java.sql.Date datasql=new java.sql.Date(date.getTime());
            Cadastro.data_nascimento=datasql;
            
        }
        catch (ParseException ex)
        {
            Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE,null, ex);
                    
        }
        
        CadastroConexao cc=new CadastroConexao();
        cc.InserirCliente();
        JOptionPane.showMessageDialog(null, "DADOS INSERIDOS COM SUCESSO!!!");
        LimparCampos ();
        
    }//GEN-LAST:event_btn_salvarActionPerformed

    public void LimparCampos ()
    {
        txt_nome.setText("");
        txt_id.setText("");
        txt_sobrenome.setText("");
        txt_idade.setText("");
        txt_data.setText("");
        cmb_sexo.setToolTipText("");
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_limpar;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JComboBox<String> cmb_sexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpn_cadastro;
    private javax.swing.JLabel lbl_cadastro;
    private javax.swing.JLabel lbl_data;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_idade;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_sexo;
    private javax.swing.JLabel lbl_sobrenome;
    private javax.swing.JFormattedTextField txt_data;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_idade;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_sobrenome;
    // End of variables declaration//GEN-END:variables
}
